### ISSUE TITLE
Footer/Header

### ISSUE THREAD

**Issue by nobodyrandom** [Developers-Foundation/dolly-v2#2]
-Harrison @nobodyrandom
-Paul @psalv

**Comment by nobodyrandom** [comment]
Resolved #1

**Comment by nobodyrandom** [comment]
@psalv when can you throw in some less?

**Comment by psalv** [comment]
@nobodyrandom on it now

**Comment by nobodyrandom** [comment]
@psalv Thanks :)
I've made a branch for us, i think it was called header if you want to use that instead.

**Comment by psalv** [comment]
Yup I'm working in that branch right now

**Comment by psalv** [comment]
Nobody look in mobile view for a while, it's not doing so hot.

**Comment by nobodyrandom** [comment]
Dont worry about mobile for now. We need to focus on getting a desktop ver out first.

On Friday, June 16, 2017, 10:14:09 AM GMT+8, Paul Salvatore <notifications@github.com> wrote:


Nobody look in mobile view for a while, it's not doing so hot.

**Comment by nobodyrandom** [comment]
@psalv 
As mentioned, need to fix the spacing + size + margin issue.

**Comment by psalv** [comment]
@nobodyrandom I'm not sure I know the issue that you're referring to.
