### ISSUE TITLE
Figure out content for Impacts Page @susieesuu

### ISSUE THREAD

**Issue by nobodyrandom** [Developers-Foundation/dolly-v2#21]
@susieesuu any updates?

**Comment by ghost** [comment]
@nobodyrandom yes - will get to u by eod today, sorry, my wifi at home is at 0.03mb/s, so i need to do this after work in the office

**Comment by ghost** [comment]
Reading Clubs
Weekly reading club meetings are held in the public primary schools in communities we serve. Part of Dolly’s mission is to engage the children in the activities that will improve their abilities academically and socially. We focus on providing reading material that inspire excellence, leadership, and increase their literacy abilities. Our initiatives has resulted in a marked improvement in the interest of children towards reading and their ability to express themselves. 
Alternatively, can write: Some of our past reading projects have included _________ for ______, ___________ for ______, and ______ for _________. (+hyperlinks for those books) 

Sponsorship Programmes
Sponsorships help children whose parents lack the financial  backbone to support their schooling. Before Dolly’s intervention, these children were unable to access desired and quality education which greatly hindered their learning processes. Over the past ___ years, Dolly’s Children Foundation has provided $_____ in sponsorships and helped ________ children go back to school. Needless to say, the children being sponsored have improved dramatically in their academic performance (on average by ____) and inherently, their social abilities and futures. 

BACK – TO – SCHOOL INITIATIVES
Basic educational tools, school uniforms, shoes, bags, etc. are provided to children with financial needs by Dolly’s Children Foundation. The initiative has also helped in bringing out-of-school children back to school by covering tuition fees and their everyday needs. This initiative has helped over 3000 children go back to school. motivate as well as boost their confidence and participation in school activities. 

TRAININGS AND WORKSHOPS FOR PUBLIC PRIMARY SCHOOL TEACHERS
Workshops and training sessions are held for teachers to bring modern education methods to them. Teaching skills are the biggest influencer to how children learn and whether the children want to learn, we have helped ______ teachers with ____ workshops with the ultimate goal of benefiting the children. These workshops include Numeracy Made Easy, 21st Century Teaching Methods, Phonics, and Understanding Your Learner. 

AFTER SCHOOL AND SUMMER TUTORING PROGRAM
Extra tutoring programs are available after school as well as during the summer to help children who are lagging behind academically. Child laborers, street children, and drop-outs are especially benefited by this program. Teachers and volunteers engage these children in academic exercises to effectively improve academic performance, reduce child labor, and child abuse. 
Community sensitization on the importance of education and child rights is often organized in remote communities. This exercise has created a platform for counseling parents/guardians of children from impoverished backgrounds who are easy target for environmental vices and such are identified quickly. Furthermore, this program not only helps children academically, but also emotionally by giving them more individual attention - making them feel loved, wanted, and significant. 

 
SCHOOL BUILDING PROJECT
School rebuilding is a project that we took on from 2015 where we refurbish public primary schools with dilapidated structures. Dolly Children Foundation move into these out-dated facilities to upgrade and equip them with the necessary educational material and infrastructure. Thus far, a block of four classes, a staff office, a library, and a store have been built from scratch. The project estimates to provide a healthy learning environment for over 500 children by the end of 2018. 


@nobodyrandom

**Comment by nobodyrandom** [comment]
@minimike511 Can you paste the content into the site please. Thanks :)

**Comment by ghost** [comment]
@minimike511 @nobodyrandom  there are blank spaces left open for content lol need to confirm stats with dolly first

**Comment by nobodyrandom** [comment]
yeah we can just put XXX for now

**Comment by nobodyrandom** [comment]
@susieesuu Is there any content for:
- http://dolly-v2.herokuapp.com/
Who we are
How to help

- http://dolly-v2.herokuapp.com/about
Values
Our vision

- http://dolly-v2.herokuapp.com/contact
LCD screens are great lol

**Comment by nobodyrandom** [comment]
@minimike511 For message from founder, use this:
```
From my experiences, I believe that access to a conducive learning environment, quality educational programmes, provision of educational aids and financial support to the less - privileged children of the communities are crucial needs, and these aforementioned values remain the core of our foundation. 

Adedolapo Osuntuyi
```
And for Missions:
```
Our Mission: 
To Inspire the African Child through educational aids and improve their socio- developmental skills through interventions centered on mental and intellectual programs
```

**Comment by ghost** [comment]
@nobodyrandom 
Homepage content is different from impact content:

Weekly reading clubs cultivate reading cultures amongst children as young as 6 years old.  

Sponsorships allow children who lack financial resources to have a chance at education. 

Textbooks, uniforms, and transportation to schools are donated to children to alleviate financial stress on their families. 

Training programs to ensure that the education provided by primary schools in Nigeria are effective and up to global standards. 

Additional education programs helps to alleviate child-care stress from working parents while enhances the children’s learning experience.

New and upgraded school facilities provide more children with the necessary infrastructure and equipment to ensure a safe and effective learning environment.

**Comment by ghost** [comment]
@nobodyrandom 
How to Help Content:

Make a direct impact on the future of a child by sponsoring their education. You will be able to communicate with the child you sponsor and we will continue to update you through monthly newsletters. 

Help improve the facilities and learning environment of Nigerian children by contributing to a school building project. We will keep you in the loop in regards to the progress and hold up our commitment to transparency by providing you with frequent updates on their progress.

Get involved with one of our other initiatives to change the lives of children in Nigeria for the better. We can allocate your donation to exactly what you want to support. Get in touch with us today!

**Comment by ghost** [comment]
also for the impact page here are is the revised content:

Weekly reading club meetings are held in the public primary schools in communities we serve. Part of Dolly’s mission is to engage the children in the activities that will improve their abilities academically and socially. We focus on providing reading material that inspire excellence, leadership, and increase their literacy abilities. Our initiatives has resulted in a marked improvement in the interest of children towards reading and their ability to express themselves. 

Sponsorships help children whose parents lack the financial  backbone to support their schooling. Before Dolly’s intervention, these children were unable to access desired and quality education which greatly hindered their learning processes. Over the past year, Dolly’s Children Foundation has provided sponsorships and helped 50 children go back to school. Needless to say, the children being sponsored have improved dramatically in their academic performance and inherently, their social abilities and futures. 

Basic educational tools, school uniforms, shoes, bags, etc. are provided to children with financial needs by Dolly’s Children Foundation. The initiative has also helped in bringing out-of-school children back to school by covering tuition fees and their everyday needs. This initiative has helped over 3000 children go back to school. motivate as well as boost their confidence and participation in school activities. 

Workshops and training sessions are held for teachers to bring modern education methods to them. Teaching skills are the biggest influencer to how children learn and whether the children want to learn, we have helped 40 teachers with workshops over the past year with the ultimate goal of benefiting the children. These workshops include Numeracy Made Easy, 21st Century Teaching Methods, Phonics, and Understanding Your Learner. 

Extra tutoring programs are available after school as well as during the summer to help children who are lagging behind academically. Child laborers, street children, and drop-outs are especially benefited by this program. Teachers and volunteers engage these children in academic exercises to effectively improve academic performance, reduce child labor, and child abuse. 
Community sensitization on the importance of education and child rights is often organized in remote communities. This exercise has created a platform for counseling parents/guardians of children from impoverished backgrounds who are easy target for environmental vices and such are identified quickly. Furthermore, this program not only helps children academically, but also emotionally by giving them more individual attention - making them feel loved, wanted, and significant. 

School rebuilding is a project that we took on from 2015 where we refurbish public primary schools with dilapidated structures. Dolly Children Foundation move into these out-dated facilities to upgrade and equip them with the necessary educational material and infrastructure. Thus far, a block of four classes, a staff office, a library, and a store have been built from scratch. The project estimates to provide a healthy learning environment for over 500 children by the end of 2018.

**Comment by ghost** [comment]
who we are: 
We are a non-profit organization that is made up of a team of individuals that are passionate about bringing affordable education to the children of Nigeria. We have helped over 5000 children in our journey thus far, we look forward to having likeminded people like you to join and support us in our road ahead.

**Comment by ghost** [comment]
contact us:

If you have any inquiries, suggestions, or concerns, please do not hesitate to get in touch with us. We look forward to hearing from you!

**Comment by ghost** [comment]
values:
I       Integrity
Provide transparency to all donors and offer equal chance at education to all eligible children. 
C     Commitment
Stay committed to the interests of African children, always placing their best interests first.
A     Accountability
Can be held accountable for all transactions, guarantees transparency to all stakeholders.
N     Nurturing
Foster a safe and healthy learning environment for all.

**Comment by ghost** [comment]
I think thats it? except for mission statement and vision, shes sending those to me tmr @nobodyrandom  (sorry for spam)

**Comment by minimike511** [comment]
what email do I put on "contact us" page?
+ all the new texts are added

**Comment by nobodyrandom** [comment]
@minimike511 adedolepo@dollychildren.org i believe if i didnt spell it wrong

**Comment by minimike511** [comment]
@nobodyrandom  should I change all the emails to that? or just contact us?
