### ISSUE TITLE
Photos for website.

### ISSUE THREAD

**Issue by nobodyrandom** [Developers-Foundation/dolly-v2#22]

**Comment by nobodyrandom** [comment]
@Fadyazmy pls provide :)

**Comment by fady-json** [comment]
@susieesuu

**Comment by nobodyrandom** [comment]
@Fadyazmy preferably the photos without overlay, borders or any fancy stuff

**Comment by nobodyrandom** [comment]
I think out of all of them only "Group 30.png" was ok LOL
