### ISSUE TITLE
Connect Donation Page to Paystack

### ISSUE THREAD

**Issue by nobodyrandom** [Developers-Foundation/dolly-v2#23]

**Comment by nobodyrandom** [comment]
@Fadyazmy did we make the paystack account yet? I cant find the password or username/email

**Comment by fady-json** [comment]
No we didn't make an account @nobodyrandom

**Comment by nobodyrandom** [comment]
OK I'll see if I can get an account asap.
btw whats dolly password to her email? did someone change it?

**Comment by nobodyrandom** [comment]
Done :)
