### ISSUE TITLE
required contents

### ISSUE THREAD

**Issue by minimike511** [Developers-Foundation/dolly-v2#30]
@susieesuu 
i) Dolly Logo (+favicon)
ii) about us logo (check zeplin and get the final design)
iii) main page buttons (what are the "learn more" button will do?)

**Comment by ghost** [comment]
@minimike511  "learn more" takes you to impact page, still waiting on design

**Comment by minimike511** [comment]
@susieesuu  all of it?

**Comment by ghost** [comment]
so @minimike511 
1. the "learn more" on "we built ____" takes you to impact
2. the "learn more" on "who we are" takes you to "about" 
3. the "learn more" on "what we do" takes you to impact

**Comment by nobodyrandom** [comment]
@minimike511 I'll generate the favicon for you

STATUS: Done on master branch. Please confirm

**Comment by nobodyrandom** [comment]
@minimike511  anymore missing content? 

Wrong minimike lol. Sorry if you end up visiting our repo.

**Comment by nobodyrandom** [comment]
Wrong @minimike lol

**Comment by minimike511** [comment]
I think we are just missing imgs and logos (logo for navbar and about us logo)

**Comment by nobodyrandom** [comment]
@susieesuu Can you provide the About Us icons? check out http://fontawesome.io/icons/ to see if those work better.
