### ISSUE TITLE
mainpage main content not visible

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#31]
"Join our Journey" content cannot be read clearly
- crop the background photo and add a 50% transparent layer over it? should i do this on photoshop and send it to you guys or can you guys add it manually? @nobodyrandom @minimike511 
- the "find out more" button looks different aka not capitalized, is the font type the same?

**Comment by nobodyrandom** [comment]
@susieesuu we should be able to do manually

**Comment by minimike511** [comment]
fixed

**Comment by nobodyrandom** [comment]
Solved on #38
