### ISSUE TITLE
photos are differently sized

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#32]
the photos of what we do are differnetly sized? can we standardize it please

**Comment by minimike511** [comment]
@susieesuu refresh? I see it that they are all equal sized?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/14024557/27959315-f22bec5a-62f4-11e7-8072-c30a6b6063e6.png)

@minimike511

**Comment by ghost** [comment]
these photos are definitely not aligned/different aspect ratios

**Comment by nobodyrandom** [comment]
@minimike try absolute height to the smallest one, then do overflow-x hidden

**Comment by minimike511** [comment]
fixed on final-fouch bransh

**Comment by nobodyrandom** [comment]
Solved on #38
