### ISSUE TITLE
About us page blurb invisible

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#33]
the font color is grey? why

**Comment by minimike511** [comment]
@susieesuu  fixed

**Comment by ghost** [comment]
@minimike511 currently not merged with dolly-v2.heroku?

**Comment by nobodyrandom** [comment]
@susieesuu we are working on pr #37  right now, will merge when all the changes are good

**Comment by nobodyrandom** [comment]
@minimike511 can you add a radial overlay on the image or something, white doesnt work very well either.

**Comment by nobodyrandom** [comment]
NVM I made a temp overlay
