### ISSUE TITLE
impacts page scroll click

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#36]
currently does not click to the right place when u click on the 1,2,3,4,5,6

**Comment by nobodyrandom** [comment]
does it not? Maybe on the next call can you show me? On my side it works.

**Comment by ghost** [comment]
e.g. when I click on the number 3 on the top bar, half the content for number 3 is blocked - I can show you!

**Comment by nobodyrandom** [comment]
Hahahahaha OK I get what you mean. I should be able to fix that

**Comment by nobodyrandom** [comment]
Solved on branch dolly-v2-pr-38 #38
