### ISSUE TITLE
button capitalization

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#45]
capitalize all the letters in the "LEARN MORE" buttons on the home page 
as well as the buttons in "How to help"

**Comment by minimike511** [comment]
@susieesuu btw for buttons in "How to help" will all the buttons lead to donate page?

**Comment by ghost** [comment]
yeah its kind of dumb - i honestly wanted to take that whole section out but lol

**Comment by nobodyrandom** [comment]
Keep them for now, we will ask dolly to advise how to proceed on this afterwards.
