### ISSUE TITLE
contact us page "send inquiry" button

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#47]
font and color, make it like the rest of the buttons

**Comment by minimike511** [comment]
@susieesuu done check plz.
@nobodyrandom are you gonna do the email set up or should I? (ex: line 209 on nob.js)

**Comment by ghost** [comment]
@minimike511 thanks, and c ca you move it inline with the captcha thing? so its not awkwardly on a separate line?

**Comment by minimike511** [comment]
@susieesuu  did
