### ISSUE TITLE
hyperlink contact page

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#48]
hyperlink email and phone number on contact page

**Comment by nobodyrandom** [comment]
@susieesuu what should the phone number hyperlink to?

@minimike511 check out `mailto::` on google for the email hyperlink

**Comment by minimike511** [comment]
@susieesuu just contact us page or both footer and navbar ones as well?

**Comment by ghost** [comment]
@nobodyrandom wait, cant you make it clickable so if i see it on my phone i can just call it? 

@minimike511 all of them would be nice!

**Comment by nobodyrandom** [comment]
@minimike511 can you try the `tel:` a tag

**Comment by nobodyrandom** [comment]
@susieesuu this would not be standard html, but we can try putting it in

**Comment by minimike511** [comment]
@susieesuu  another thing I need a right phone number ( as you can see 3 different phone numbers...)

**Comment by ghost** [comment]
@minimike511  +234 818 689 1611

**Comment by nobodyrandom** [comment]
@minimike511 can you use the `link.php` and the `linkPrint.php`

**Comment by minimike511** [comment]
@nobodyrandom  don\t use tel?

**Comment by nobodyrandom** [comment]
Hmm?
