### ISSUE TITLE
About Us page icons for values

### ISSUE THREAD

**Issue by ghost** [Developers-Foundation/dolly-v2#53]
pls get rid of the circle pls

**Comment by minimike511** [comment]
@susieesuu like this? (check the web)

**Comment by ghost** [comment]
@minimike511 they are no longer centred, do u see the gaps between the icons and the dashes?/ and they are also not centred with their descriptions
<img width="1275" alt="screen shot 2017-08-02 at 9 24 24 pm" src="https://user-images.githubusercontent.com/14024557/28901832-0147cffe-77c9-11e7-8ae3-4acce767e672.png">

**Comment by minimike511** [comment]
@susieesuu check
