### ISSUE TITLE
@nodobyrandom donate custom value

### ISSUE THREAD

**Issue by minimike511** [Developers-Foundation/dolly-v2#59]
@nobodyrandom is the donate other value always gives -1?

**Comment by nobodyrandom** [comment]
Yes, does it work?

**Comment by nobodyrandom** [comment]
On the script it reads it as -1 , but when it submits it should take the real value

**Comment by minimike511** [comment]
@nobodyrandom my YUI is not working..... (both js and css)

**Comment by nobodyrandom** [comment]
Lets hop on a call your tomorrow morning?

**Comment by minimike511** [comment]
sure
